### ISSUE TITLE
add developer training part 2

### ISSUE THREAD

**Issue by onuryukselen** [ViaScientific/vfdocs#14]
Please check out the developer tutorial 2-3-4 content,
https://github.com/ViaScientific/vfdocs/commit/ed947fee2386ff99bb9b45ce3cef7c91f7844e5a

I would like to address these questions in multiple tutorials like this one.

https://github.com/ViaScientific/vfdocs/blob/development/docs/ViaFoundry/demo_developer_tutorial.md

**Comment by Jldavis6** [comment]
Tutorial page and three separate FAQ pages (Process FAQs, Pipeline FAQs, Third Party FAQs) posted to Development branch.
